### PR TITLE
Scratch/tejasrai/message utilities

### PR DESCRIPTION
**Pull request by tenzincrouch**
This PR adds the message utilities functions used by the ground control software and peripheral computer to the rover messages repo for shared use.

## 

## How has this been tested?

This was tested with the paper mission and through manual tests. Unit tests are yet to be written.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have read and followed the `CONTRIBUTING.md` file
- [x] I have applied the .clang-format file to my changes
- [x] I have commented my code using Doxygen style comments (see Contributing MD for examples), particularly in hard-to-understand areas
- [x] I have made corresponding changes to the design documentation 
- [x] I have updated any relevant parameters in the internal ICD
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If this is a bug-fix, I have added tests that can catch similar bugs in the future
- [x] New and existing unit tests pass locally with my changes
- [ ] For cfe apps I have reserved an empty address for my msgs_ids and perf_ids from the [tracking list](https://docs.google.com/spreadsheets/d/1yRUhNTRBOiGLswlsWftNaYlwGKDeNQ_fCnDYFrc_7fU/edit#gid=772812381) and checked that it does not clash with other apps
- [x] For new added message types, there is a timestamp included via either an explicit timestamp variable in the struct or buried in the a tlmHeader.

### CODE REVIEW

**Comment by indraneelpatil** [comment]
@tejasrai25 Can you please review this and help merge this to main?

cc  : @bdcmu  @jtingyu7

**Comment by tejasrai25** [comment]
@indraneelpatil this branch has been integrated with the go modules in the MCS. It is passing all the existing tests. It is ready to be merged.
cc : @bdcmu @jtingyu7

**Review by tenzincrouch — COMMENTED** [review]
LGTM

**Comment by tenzincrouch** [comment]
Merging with admin privileges after review from multiple developers.

**Pull request merged**
