### PR TITLE
Add JSON Parsers for Telemetry Message to C

### PR DESCRIPTION
**Pull request by epicstar**
## Description

The main purpose of this is to quickly be able to send data between technologies from the rover to any other software.

The main purpose is PlanetaryRobotics/moonranger-mission-control#286.

The code additions are as follows:
* in utilities.c, add C struct -> JSON parsing logic to the telemetry
* go code will call the following: `CFE_SB_MsgId_t ParseTelemetry(void* MsgPtr, char **outJson);` to parse the telemetry UDP packet

## 

The business case of this is to ensure that if any telemetry messages change, less technical effort is needed to coordinate with @PlanetaryRobotics/lunarrangers so we are no longer blocked. In addition, this reduces the time to parse telemetry messages from hours to less than an hour.

Second, having the parsing code in the same codebase that defines the message structs will allow future cohorts to easily make changes to the messages codebase so that any changes positively affect the organization.

No structs have been added, but [cJSON](https://github.com/DaveGamble/cJSON) was added into the repository as a code dependency. A README.md was made to help you understand the purpose and how it was consumed.

## How has this been tested?

[moonranger-mission-control](https://github.com/PlanetaryRobotics/moonranger-mission-control) has unit tests that will pass or fail depending on the changes. There may also be build issues.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have read and followed the `CONTRIBUTING.md` file
- [ ] I have applied the .clang-format file to my changes
- [x] I have commented my code using Doxygen style comments (see Contributing MD for examples), particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the design documentation 
- [ ] I have updated any relevant parameters in the internal ICD
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If this is a bug-fix, I have added tests that can catch similar bugs in the future
- [ ] New and existing unit tests pass locally with my changes
- [ ] For cfe apps I have reserved an empty address for my msgs_ids and perf_ids from the [tracking list](https://docs.google.com/spreadsheets/d/1yRUhNTRBOiGLswlsWftNaYlwGKDeNQ_fCnDYFrc_7fU/edit#gid=772812381) and checked that it does not clash with other apps
- If any message is changed, removed, or added:
  - [ ] Please contact `#software` on Slack about the change(s)
  - [ ] **ONLY IF TELEMETRY MESSAGE** (for now): `./message-utilities/src/utilities.c` is updated with the correct field(s) properly marshalled to JSON **(IMPORTANT)**
  - If a new struct/message is added:
    - [ ] There is a timestamp included via either an explicit timestamp variable in the struct or buried in the a tlmHeader
  - If any of the existing struct's properties change in any way (property name change, property moves around in the struct, property removed):
    - [ ] **Breaking change** is checkmarked above as any change will affect every software downstream

### CODE REVIEW

**Review by lincsmythe — APPROVED** [review]
P+:
All code changes are well written and the functionality of the MCs system performs as expected. Further, the backend unit tests were run to confirm that all tests checked run (not including the skipped tests). There's currently been no CI/CD issues as mentioned in the PR, therefore, I assess this code review as approved and can be merged.

**Comment by epicstar** [comment]
turns out not ready...

**Comment by epicstar** [comment]
we need to merge main into the feature branch

**Review by tenzincrouch — APPROVED** [review]
Approved. 

@epicstar - I am a little confused as to the benefit of these changes noting that utilities.c still has a function for every telemetry message type, but if you are confident it will be easier then happy to go ahead.

**Pull request merged**
